server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/house_deed_pavilion?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  flyway:
    # 关键配置：允许在非空数据库上创建历史表并基线化
    baseline-on-migrate: true
    # 可选：指定基线版本（默认是 1）
    baseline-version: 1
    # 可选：如果数据库有默认 schema，指定 schema 名称（如 MySQL 通常不填）
    # schemas: house_deed_pavilion
mybatis-plus:
  mapper-locations: classpath*:com/house/deed/pavilion/module/**/mapper/*.xml
  type-aliases-package: com.house.deed.pavilion.module.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  redis:
    host: 192.168.1.3 # Redis服务器地址
    port: 6379       # 端口
    password:        # 密码（如有）
    database: 0      # 数据库索引（默认0）
    timeout: 3000ms  # 连接超时时间
    lettuce:
      pool:
        max-active: 16  # 最大连接数
        max-idle: 8     # 最大空闲连接
        min-idle: 4     # 最小空闲连接
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true